# Generated by Django 4.1.2 on 2022-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='producto.categoria'),
        ),
    ]
