# Generated by Django 4.1.2 on 2022-10-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_credito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
