# Generated by Django 4.1.2 on 2022-10-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_alter_credito_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Pagado', 'Pagado')], default='Pendiente', max_length=100),
        ),
    ]
