# Generated by Django 4.1.2 on 2022-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_alter_credito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='modificacion',
            field=models.BooleanField(default=False),
        ),
    ]
