# Generated by Django 4.1.2 on 2022-10-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0005_credito_modificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='modificacion',
        ),
    ]
